apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: alessandroaffinito/spring-demo:release-01
        resources:
          limits:
            memory: "128Mi"
            cpu: "0m"
        ports:
        - containerPort: 3050
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo
spec:
  selector:
    app: spring-demo
  ports:
  - port: 8080
    targetPort: 8080
